Create SMB share and mount it on docker-machine start.

diff --git a/bin/dsh b/bin/dsh
--- a/bin/dsh
+++ b/bin/dsh
@@ -995,6 +995,7 @@ docker_machine_create ()
 			docker-machine create --driver=virtualbox \
 				--virtualbox-disk-size "$DEFAULT_MACHINE_VBOX_HDD" \
 				--virtualbox-memory "$DEFAULT_MACHINE_VBOX_RAM" \
+				--virtualbox-hostonly-cidr "$DRUDE_SUBNET" \
 				--virtualbox-no-share \
 				"$machine_name"
 			;; #-- end virtualbox
@@ -1209,11 +1210,47 @@ docker_machine_mount_nfs ()
 	done
 }
 
+# Method to create the user and SMB network share on Windows.
+# @param share_name, path
+smb_share_add()
+{
+	# Add SMB share if it does not exist.
+	command_share="net share ${1} || net share ${1}=${2} /grant:${USERNAME},FULL"
+	echo-green "Adding docker SMB share..."
+	winsudo "$command_share"
+}
+
+# Method to mount the SMB share in Docker machine.
+# @param path, password
+smb_share_mount()
+{
+	DOCKER_MACHINE_IP=$(docker-machine ip ${DOCKER_MACHINE_NAME})
+	network_id=$("$vboxmanage" showvminfo ${DOCKER_MACHINE_NAME} --machinereadable | grep hostonlyadapter | cut -d'"' -f2)
+	DOCKER_HOST_IP=$("$vboxmanage" list hostonlyifs | grep "${network_id}" -A 3 | grep IPAddress |cut -d ':' -f2 | xargs)
+
+	command_mount="sudo mkdir -p /$1 && sudo mount -t cifs -o noperm,sec=ntlm,username='${USERNAME}',pass='$2',dir_mode=0777,file_mode=0777 //${DOCKER_HOST_IP}/$1 /$1"
+	# sudo mount -t cifs -o noperm,sec=ntlm,username=docker,pass="P@ssW0rd1!",dir_mode=0777,file_mode=0777 //192.168.99.1/projects2 /c/projects2
+	docker-machine ssh ${DOCKER_MACHINE_NAME} "$command_mount"
+}
+
 docker_machine_mount_smb ()
 {
 	# add share \\hostname\c writable to current user
 	# ask user for his password
 	# use his password for mount -t cifs ...
+
+	local DRIVES=$(wmic logicaldisk get name | sed 's/\r//g')
+	read -s -p "Enter Windows account password: " PASSWORD
+
+	for DRIVE in ${DRIVES}; do
+		if [ "$DRIVE" != "Name" ]; then
+			local MOUNT_POINT=$(cygpath -u $DRIVE | sed 's/^\/cygdrive\///')
+			smb_share_add "$MOUNT_POINT" "$DRIVE" && \
+				smb_share_mount "$MOUNT_POINT" "$PASSWORD" || \
+				(echo-red "Error creating share" && exit 1)
+		fi
+	done
+
 	return
 }
 
