Lots of minor refactoring
Cache results of is_linux check to make multiple checks faster and make is_windows faster
Get rid of not needed functions: is_vagrant, is_vagrantfile_absent, check_docker, check_docker_compose
binary_found renamed to check_binary_found to reflect it's actions
get_drush_path renamed to check_drush_path to reflect it's actions
Misc messaging and comments updates

diff --git a/bin/dsh b/bin/dsh
--- a/bin/dsh
+++ b/bin/dsh
@@ -99,18 +99,7 @@ get_current_relative_path ()
 	echo $pathdiff
 }
 
-# Check that command is run inside project folder
-get_drush_path ()
-{
-	local pathdiff=$(get_current_relative_path)
-	if [[ "$(pwd)" == "$pathdiff" ]]; then
-		echo-red "dsh: This command must be run inside Drupal's document root"
-		return 1
-	fi
-	return 0
-}
-
-# Removes invisible residue from the string that remains leftover sometimes
+# Removes invisible residue from the string that remains leftover in Babun+docker-compose sometimes
 # @param $1 string to cleanup
 # @return clean string
 clean_string ()
@@ -152,26 +141,28 @@ get_container_id ()
 
 is_linux ()
 {
-	res=$(uname | grep 'Linux')
+	if [[ $IS_LINUX != "" ]] && [ $IS_LINUX -eq 1 ]; then return 0; fi
+
+	local res=$(uname | grep 'Linux')
 	if [[ ! "$res" == '' ]]; then
 		return 0;
 	else
+		IS_LINUX=1
 		return 1;
 	fi
 }
 
 is_windows ()
 {
-	res=$(uname | grep 'MINGW32_NT')
-	if [[ "$res" != '' ]]; then
-		echo-red "dsh: Running from Git Bash is not supported. Please get Babun http://babun.github.io"
-		exit
-	fi
-
-	res=$(uname | grep 'CYGWIN_NT')
+	local res=$(uname | grep 'CYGWIN_NT')
 	if [[ "$res" != '' ]]; then
 		return 0;
 	else
+		res=$(uname | grep 'MINGW32_NT')
+		if [[ "$res" != '' ]]; then
+			echo-red "dsh: Running from Git Bash is not supported"
+			exit 1
+		fi
 		return 1;
 	fi
 }
@@ -189,7 +180,7 @@ is_boot2docker ()
 
 is_mac ()
 {
-	res=$(uname | grep 'Darwin')
+	local res=$(uname | grep 'Darwin')
 	if [[ ! "$res" == '' ]]; then
 		return 0;
 	else
@@ -197,7 +188,7 @@ is_mac ()
 	fi
 }
 
-# checks if binary exists and callable in PATH
+# searches if binary exists and callable in PATH
 is_binary_found ()
 {
 	if [[ "$1" == "" ]]; then
@@ -213,31 +204,11 @@ is_binary_found ()
 	fi
 }
 
-binary_found ()
+# checks if binary exists and fails is it isn't
+check_binary_found ()
 {
 	is_binary_found $1
 	if_failed "$1 executable not found."
-}
-
-# check that vagrant binary exists
-is_vagrant ()
-{
-	if is_linux ; then return 1; fi
-	if is_boot2docker ; then return 1; fi
-	binary_found 'vagrant';
-	return $?
-}
-
-# check that docker-compose binary exists
-check_docker_compose ()
-{
-	binary_found 'docker-compose';
-}
-
-# check that docker binary exists
-check_docker ()
-{
-	binary_found 'docker';
 }
 
 is_docker_running ()
@@ -256,7 +227,7 @@ is_docker_running ()
 	else
 		# Then use netcat to check the host:port
 		# nc on Mac needs -G for the connections timeout argument.
-		binary_found 'nc'
+		check_binary_found 'nc'
 		if [[ $DOCKER_HOST == "" ]]; then
 			echo-red "dsh: $DOCKER_HOST variable is empty"
 			return 1
@@ -307,8 +278,8 @@ ver_to_int ()
 
 check_docker_running ()
 {
-	check_docker
-	check_docker_compose
+	check_binary_found 'docker'
+	check_binary_found 'docker-compose'
 	check_yml
 	if ! is_docker_running; then
 		echo-red "dsh: Unable to connect to the docker daemon";
@@ -316,44 +287,33 @@ check_docker_running ()
 	fi
 }
 
-is_vagrantfile_absent ()
-{
-	vagrant_path=$(upfind "Vagrantfile")
-	if [[ "$vagrant_path" == "" ]] ; then
-		echo-red "dsh: Vagrantfile not found in your directory tree"
-		return 0
-	fi
-
-	return 1
-}
-
-# Checks if yml or vagrantfile (win, mac) is absent
-is_yml_absent ()
+# Check that docker-compose.yml (and Vagrantfile on Win/Mac) present. Fail otherwise
+check_yml()
 {
 	yml_path=$(yml_get_path)
 	if [[ "$yml_path" == "" ]] ; then
-		echo-red "dsh: docker-compose.yml not found in your directory tree"
-		return 0
+		echo-red "dsh: docker-compose.yml was not found in your directory tree"
+		exit 1
 	fi
 
 	if is_linux ; then
-		return 1; # linux does not need vagrant
+		return; # linux does not need vagrant
 	fi
 
 	vagrant_path=$(upfind "Vagrantfile")
 	if [[ "$vagrant_path" == "" ]] ; then
-		echo-red "dsh: Vagrantfile not found in your directory tree"
-		return 0
+		echo-red "dsh: Vagrantfile was not found in your directory tree"
+		exit 1
 	fi
-
-	#if we got here files are present
-	return 1
 }
 
-check_yml() 
+# Check that command is run inside project folder
+check_drush_path ()
 {
-	if is_yml_absent; then
-		exit 2
+	local pathdiff=$(get_current_relative_path)
+	if [[ "$(pwd)" == "$pathdiff" ]]; then
+		echo-red "dsh: This command must be run inside Drupal's document root"
+		exit 1
 	fi
 }
 
@@ -389,6 +349,7 @@ _notify ()
 	fi
 }
 
+# Make sure $DOCKER_HOST is not empty
 check_docker_host ()
 {
 	if is_linux ; then return 0; fi
@@ -546,7 +507,11 @@ bash_comp_words ()
 up ()
 {
 	check_yml
-	if is_vagrant ; then
+	if is_linux || is_boot2docker; then
+		_start_containers
+	else
+		check_binary_found vagrant
+		local started
 		if ! is_docker_running; then
 			echo-green "dsh: Starting vagrant vm..."
 			vagrant up
@@ -557,8 +522,6 @@ up ()
 		if [ $started -eq 0 ] ; then
 			_start_containers
 		fi
-	elif ( is_boot2docker || is_linux ) ; then
-		_start_containers
 	fi
 }
 
@@ -573,10 +536,10 @@ down ()
 halt ()
 {
 	check_docker_running
-	if is_vagrant ; then
-		vagrant halt
-	elif ( is_boot2docker || is_linux ) ; then
+	if is_linux || is_boot2docker; then
 		_stop_containers
+	else
+		vagrant halt
 	fi
 }
 
@@ -592,15 +555,15 @@ restart ()
 reload ()
 {
 	check_yml
-	if is_vagrant ; then
+	if is_linux || is_boot2docker; then
+		_start_containers
+	else
+		check_binary_found vagrant
 		echo-green "dsh: Restarting vagrant vm..."
 		vagrant reload
-		started=$?
-		if [ $started -eq 0 ] ; then
+		if [ $? -eq 0 ]; then
 			_start_containers
 		fi
-	elif ( is_boot2docker || is_linux ) ; then
-		_start_containers
 	fi
 }
 
@@ -621,10 +584,10 @@ vmstat ()
 {
 	local vagrant_path=$(upfind Vagrantfile)
 	if [[ $vagrant_path == "" ]]; then
-		echo-red "Vagrantfile not found"
+		echo-red "dsh: Vagrantfile was not found in your directory tree"
 		exit 1
 	fi
-	binary_found vboxmanage
+	check_binary_found vboxmanage
 	local machine_id="${vagrant_path}/.vagrant/machines/boot2docker/virtualbox/id"
 	if [ ! -f $machine_id ]; then
 		echo-red "Could not find id file $machine_id"
@@ -645,7 +608,7 @@ install_prerequisites ()
 	testing_warn
 	if is_docker_running; then
 		if is_linux; then
-			stopcmd="'dsh stop"
+			stopcmd="'dsh stop'"
 		else
 			stopcmd="'dsh halt'"
 		fi
@@ -653,9 +616,7 @@ install_prerequisites ()
 		_confirm "Continue without stopping Docker?"
 	fi
 
-	if ! is_linux; then
-		echo-green "Installing prerequisites..."
-	fi
+	echo-green "Installing prerequisites..."
 
 	if is_windows ; then
 		# installing prerequisites
@@ -838,6 +799,7 @@ install ()
 # Update container images
 update_images ()
 {
+	check_docker_running
 	docker_compose pull
 	up
 }
@@ -847,84 +809,85 @@ update_boot2docker ()
 {
 	testing_warn
 	if ! is_tty; then
-		echo "'update' is not allowed in a non-interactive environment."
+		echo-red "dsh: update is not allowed in a non-interactive environment."
 		return 1
 	fi
 
-	if is_boot2docker ; then
-		echo-yellow "dsh: Updating from inside boot2docker will not update you VM box"
+	if ! is_windows && ! is_mac ; then
+		echo-red "dsh: drude boot2docker box update should be used on Mac and Win only"
+		return 1
+	fi
+
+	# don't download update if we can't locate Vagrantfile
+	vagrant_path=$(upfind "Vagrantfile")
+	if [[ "$vagrant_path" == "" ]] ; then
+		echo-red "dsh: Vagrantfile not found in your directory tree"
+		return 1
 	fi
 
 	local cwd=$(pwd)
-	# run boot2docker update only on Mac and Win
-	if ! is_linux ; then
-		echo-green "Installing boot2docker update..."
+	echo-green "Installing boot2docker update..."
 
-		# get current version
-		local b2d_version=$(cat $DRUDE_B2D_VERSION 2>/dev/null)
-		if [[ "$b2d_version" = "" ]]; then b2d_version="undetected version"; fi
+	# get current version
+	local b2d_version=$(cat $DRUDE_B2D_VERSION 2>/dev/null)
+	if [[ "$b2d_version" = "" ]]; then b2d_version="undetected version"; fi
 
-		# get new version
-		local b2d_new_version
-		b2d_new_version=$(curl -kfsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/VERSION)
-		if_failed "Could not get latest boot2docker version. Please check your internet connection"
+	# get new version
+	local b2d_new_version
+	b2d_new_version=$(curl -kfsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/VERSION)
+	if_failed "Could not get latest boot2docker version. Please check your internet connection"
 
-		# update boot2docker
+	# update boot2docker
+	local forced_update='';
+	local destroy_box=1;
+	if [[ "$1" == "-f" ]] || [[ "$2" == "-f" ]]; then forced_update="(forced update)"; fi
+	if [[ "$1" == "-n" ]] || [[ "$2" == "-n" ]]; then destroy_box=0; fi
 
-		local forced_update='';
-		local destroy_box=1;
-		if [[ "$1" == "-f" ]] || [[ "$2" == "-f" ]]; then forced_update="(forced update)"; fi
-		if [[ "$1" == "-n" ]] || [[ "$2" == "-n" ]]; then destroy_box=0; fi
-
-		if [[ ! "$b2d_new_version" == "$b2d_version" ]] || [ -n "$forced_update" ]; then
-			echo -e "boot2docker update available: ${green}$b2d_new_version $forced_update${NC} (you have $b2d_version)."
-			if [ $destroy_box -eq 1 ]; then
-				echo -e "${red}Update will destroy and re-create your Vagrant box${NC} (run with -n if you know re-creation can be skipped this time)"
-				_confirm "Please confirm."
-			else
-				echo-green "Vagrant box will not be re-created"
-			fi
-
-			# don't download update if we can't locate Vagrantfile
-			if is_vagrantfile_absent ; then return 1; fi
-			cd $vagrant_path
-			echo "Vagrantfile is found in "$(pwd)
-
-			echo-green "dsh: Downloading boot2docker install script..."
-			local b2d_setup_script
-			b2d_setup_script=$(curl -kfsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/scripts/setup.sh)
-			if_failed  "Could not get latest boot2docker version. Please check your internet connection"
-
-			echo "dsh: Creating backups in $DRUDE_CONFIG_BACKUP_DIR..."
-			local timestamp=$(date +%s)
-			cp -v Vagrantfile $DRUDE_CONFIG_BACKUP_DIR/Vagrantfile.$timestamp && \
-			cp -v vagrant.yml $DRUDE_CONFIG_BACKUP_DIR/vagrant.yml.$timestamp
-			if_failed "Unable to perform configuration backups. Aborting..."
-			# contingency. remove old backups
-			rm "$DRUDE_CONFIG_DIR/Vagrantfile.*" 2>/dev/null
-			rm "$DRUDE_CONFIG_DIR/vagrant.yml.*" 2>/dev/null
-
-			if [ $destroy_box -eq 1 ]; then
-				echo-yellow "dsh: Destroying vagrant box..."
-				vagrant destroy -f
-			fi
-
-			echo-green "dsh: Running boot2docker install script..."
-			# calling bash interactively
-			bash <(echo "$b2d_setup_script")
-
-			if_failed "boot2docker install script error"
-
-			# update recorded boot2docker version
-			echo $b2d_new_version > $DRUDE_B2D_VERSION
-			echo -e "boot2docker ${green}$b2d_new_version${NC} was installed"
+	if [[ ! "$b2d_new_version" == "$b2d_version" ]] || [ -n "$forced_update" ]; then
+		echo -e "boot2docker update available: ${green}$b2d_new_version $forced_update${NC} (you have $b2d_version)."
+		if [ $destroy_box -eq 1 ]; then
+			echo -e "${red}Update will destroy and re-create your Vagrant box${NC} (run with -n if you know re-creation can be skipped this time)"
+			_confirm "Please confirm."
 		else
-			echo "boot2docker $b2d_version you have is the latest version (-f to force update)"
+			echo-green "Vagrant box will not be re-created"
 		fi
+
+		cd $vagrant_path
+		echo "Vagrantfile is found in "$(pwd)
+
+		echo-green "dsh: Downloading boot2docker install script..."
+		local b2d_setup_script
+		b2d_setup_script=$(curl -kfsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/scripts/setup.sh)
+		if_failed  "Could not get latest boot2docker version. Please check your internet connection"
+
+		echo "dsh: Creating backups in $DRUDE_CONFIG_BACKUP_DIR..."
+		local timestamp=$(date +%s)
+		cp -v Vagrantfile $DRUDE_CONFIG_BACKUP_DIR/Vagrantfile.$timestamp && \
+		cp -v vagrant.yml $DRUDE_CONFIG_BACKUP_DIR/vagrant.yml.$timestamp
+		if_failed "Unable to perform configuration backups. Aborting..."
+		# contingency. remove old backups
+		rm "$DRUDE_CONFIG_DIR/Vagrantfile.*" 2>/dev/null
+		rm "$DRUDE_CONFIG_DIR/vagrant.yml.*" 2>/dev/null
+
+		if [ $destroy_box -eq 1 ]; then
+			echo-yellow "dsh: Destroying vagrant box..."
+			vagrant destroy -f
+		fi
+
+		echo-green "dsh: Running boot2docker install script..."
+		# calling bash interactively
+		bash <(echo "$b2d_setup_script")
+
+		if_failed "boot2docker install script error"
+
+		# update recorded boot2docker version
+		echo $b2d_new_version > $DRUDE_B2D_VERSION
+		echo -e "boot2docker ${green}$b2d_new_version${NC} was installed"
+	else
+		echo "boot2docker $b2d_version you have is the latest version (-f to force update)"
 	fi
 
-	# Update drude
-	cd $cwd # we need to bo back if we were installing boot2docker
+	cd $cwd # go back where we were
 }
 
 # Update dsh itself
@@ -1068,7 +1031,7 @@ _run ()
 mysql ()
 {
 	check_docker_running
-	if ! get_drush_path; then return; fi
+	check_drush_path
 	_run $(get_mysql_connect)" -A" # -A option to speed up mysql load
 }
 
@@ -1077,7 +1040,7 @@ mysql ()
 mysql_import ()
 {
 	check_docker_running
-	if ! get_drush_path; then return; fi
+	check_drush_path
 
 	local confirm=1
 	if [[ "$1" == "-y" ]] || [[ "$2" == "-y" ]]; then
@@ -1141,7 +1104,6 @@ mysql_import ()
 clear_cache ()
 {
 	check_docker_running
-	#if ! get_drush_path; then return; fi
 	local type='all'
 	if [[ ! "$1" == "" ]]; then
 		type=$1
@@ -1186,7 +1148,7 @@ init ()
 	export PROJECT_ROOT=$(yml_get_path)
 	local init_script="$PROJECT_ROOT/.drude/scripts/drude-init.sh"
 	if [[ -f $init_script ]]; then
-		exec $init_script $@
+		exec $init_script "$@"
 	else
 		echo "Project init script is missing: $init_script"
 		exit 1
@@ -1215,22 +1177,7 @@ remove ()
 	if [[ $1 == "" ]]; then
 		_confirm "[!] This will delete all project containers including the DB one. You will have to re-import DB.";
 	fi
-
-	if is_vagrant ; then
-		if ! is_docker_running; then
-			echo-green "dsh: Starting vagrant vm..."
-			vagrant up
-			started=$?
-		else
-			started=0
-		fi
-
-		if [ $started -eq 0 ] ; then
-			_remove_containers $*
-		fi
-	elif ( is_boot2docker || is_linux ) ; then
-		_remove_containers $*
-	fi
+	_remove_containers $*
 }
 
 # Reset container(s) (stop, remove, up)
