1.99.40. 'dsh vm <command>' new subset of commands to control vm
Removed commands: dsh halt, dsh reload

diff --git a/bin/dsh b/bin/dsh
--- a/bin/dsh
+++ b/bin/dsh
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-DSH_VERSION=1.99.32
+DSH_VERSION=1.99.40
 
 # Console colors
 red='\033[0;91m'
@@ -609,20 +609,17 @@ show_help ()
 	fi
 	printh "stop (down) [-a (--all)]" "Stop project services. -a stops all containers except Drude system services"
 	printh "restart	[service]" "Restart all current project services or specified service"
-	if ! is_linux; then
-		printh "reload" "Restart docker machine"
-		printh "halt" "Stop docker machine"
-	fi
 	printh "status (st, ps) [-a (--all)]" "Show project services status. -a shows all running containers"
 	printh "reset [service]" "Recreate service(s). If no parameter given recreates all project services."
 	printh "" "See ${yellow}'dsh help reset'${NC} for more details on resetting Drude system services."
 	printh "remove [service]" "Remove project or system services. See ${yellow}'dsh help remove'${NC}"
+	! is_linux && \
+		printh "vm <command>" "Control docker machine vm. See ${yellow}'dsh help vm'${NC} for commands list" "yellow"
 	echo
 	printh "bash [service]" "Open bash to service container. Defaults to ${yellow}'cli'${NC} service"
 	printh "exec (run) <command> [params]" "Execute a command in ${yellow}'cli'${NC} service container"
-	printh "logs [service]" "Show docker logs for service container"
-	echo
 	printh "exec-url <url>" "Download script from URL and run it. URL should be public."
+	printh "logs [service]" "Show docker logs for service container"
 	echo
 	printh "drush [command] [options...]" "Execute Drush command in ${yellow}'cli'${NC} service"
 	printh "cc [cache_type]" "Clear Drupal 7 caches ('dsh cc' is equal to 'dsh cc all')"
@@ -642,13 +639,6 @@ show_help ()
 	echo
 	printh "cleanup [--hard]" "Cleanup images to save space (--hard will also remove all stopped containers)"
 	printh "sysinfo" "Show diagnostics information for bug reporting"
-	if ! is_linux && [[ "$DOCKER_MACHINE_PROVIDER" == "virtualbox" ]]; then
-		printh "vmstat" "Show virtualbox vm usage statistics"
-	fi
-	if ! is_linux; then
-		printh "ip" "Show Drude's docker machine ip address"
-		printh "env" "Display the commands to set up the environment for the Docker client"
-	fi
 	printh "version	(v, -v)" "Print dsh version. [v, -v] - prints short version"
 
 	# Show list of custom commands and their help if available
@@ -688,7 +678,7 @@ show_help_ssh-add ()
 
 show_help_reset ()
 {
-	echo-green "dsh reset -  Recreate services/containers. Equal to dsh stop, dsh remove, dsh start"
+	echo-green "dsh reset - Recreate services/containers. Equal to dsh stop, dsh remove, dsh start"
 	echo
 	echo-green "Parameters: one or more service names. Examples:"
 	echo "	dsh reset web		Restart 'web' service"
@@ -707,7 +697,7 @@ show_help_reset ()
 
 show_help_remove ()
 {
-	echo-green "dsh remove -  Remove services/containers"
+	echo-green "dsh remove - Remove services/containers"
 	echo
 	echo -e "${green}Parameters:${NC} one or more service names."
 	echo-green "Examples:"
@@ -718,7 +708,7 @@ show_help_remove ()
 
 show_help_install ()
 {
-	echo-green "dsh install -  Automated install of Drude system components"
+	echo-green "dsh install - Automated install of Drude system components"
 	echo
 	printh "dsh install prerequisites" "Install software required to run Drude"
 	printh "dsh install drude-config" "Download latest default docker-compose.yml"
@@ -728,11 +718,31 @@ show_help_install ()
 
 show_help_update ()
 {
-	echo-green "dsh update -  Automated update of Drude system components"
+	echo-green "dsh update - Automated update of Drude system components"
 	echo
 	printh "dsh update prerequisites" "Update software required to run Drude"
 	printh "dsh update images" "Update container images <https://docs.docker.com/engine/understanding-docker/#what-is-docker-s-architecture>"
 	printh "dsh update dsh" "Update dsh itself (Used to be named: dsh self-update)"
+	echo
+}
+
+show_help_vm ()
+{
+	echo-green "dsh vm <command> - Control docker machine directly"
+	echo
+	echo-green "Commands:"
+	printh "start" "Start a machine"
+	printh "restart" "Restart a machine"
+	printh "status" "Get the status of a machine"
+	printh "stop" "Stop a machine"
+	printh "ssh" "Log into or run a command on a machine with SSH"
+	printh "stats" "Show current HDD/RAM usage stats"
+	printh "kill" "Forcibely stop a machine"
+	printh "ip" "Get the IP address of a machine"
+	printh "env" "Display the commands to set up the shell for direct use of Docker client"
+	echo
+	printh "ram" "Display machine's memory size"
+	printh "ram [megabytes]" "Set machine's memory size. Default is 1024"
 	echo
 }
 
@@ -760,8 +770,12 @@ bash_comp_words ()
 			echo "prerequisites images dsh"
 			exit 0
 			;;
+		vm)
+			echo "start restart status stop ssh stats kill ip env ram"
+			exit 0
+			;;
 		dsh)
-			echo "start up stop down halt reload restart status reset remove bash exec logs run mysql mysql-import exec-url drush drupal behat ssh-add install update self-update version cleanup vmstat system-information sysinfo"
+			echo "start up stop down restart status reset remove bash exec logs run mysql mysql-import exec-url drush drupal behat ssh-add install update self-update version cleanup vm sysinfo"
 			exit 0
 			;;
 		*)
@@ -819,13 +833,11 @@ docker_machine_destroy ()
 is_docker_machine_exist ()
 {
 	docker-machine ls | grep "$DOCKER_MACHINE_NAME" 1>/dev/null 2>/dev/null
-	return $?
 }
 
 docker_machine_env ()
 {
 	eval $(docker-machine env "$DOCKER_MACHINE_NAME")
-	return $?
 }
 
 # Stop docker machine
@@ -833,7 +845,6 @@ docker_machine_stop ()
 {
 	check_binary_found 'docker-machine'
 	docker-machine stop "$DOCKER_MACHINE_NAME"
-	return $?
 }
 
 docker_machine_start ()
@@ -871,7 +882,76 @@ docker_machine_mounts ()
 	fi
 }
 
-#------------------------------- User Commands -----------------------------------
+#------------------------------- VM Commands -----------------------------------
+
+vm ()
+{
+	check_binary_found 'docker-machine'
+	! is_docker_machine_exist && echo-yellow "Docker machine is not created yet" && return 1
+	case $1 in
+		start)
+			! is_docker_machine_running && docker_machine_start || echo "Machine \"$DOCKER_MACHINE_NAME\" is already running."
+			;;
+		restart)
+			docker_machine_stop && docker_machine_start
+			;;
+		status)
+			docker-machine status "$DOCKER_MACHINE_NAME"
+			;;
+		stop)
+			docker_machine_stop
+			;;
+		ssh)
+			docker-machine ssh "$DOCKER_MACHINE_NAME"
+			;;
+		stats)
+			vm-stats
+			;;
+		kill)
+			docker-machine kill "$DOCKER_MACHINE_NAME"
+			;;
+		ip)
+			docker-machine ip "$DOCKER_MACHINE_NAME"
+			;;
+		env)
+			docker-machine env "$DOCKER_MACHINE_NAME"
+			;;
+		ram)
+			shift
+			vm-ram "$@"
+			;;
+		*)
+			show_help_vm
+			;;
+	esac
+}
+
+vm-stats ()
+{
+	check_docker_running
+	if ! is_binary_found vboxmanage; then
+		echo-error "vboxmanage was not found" && exit 1
+	fi
+	metrics="CPU/Load/User,CPU/Load/Kernel,Disk/Usage/Used,RAM/Usage/Used,Net/Rate/Rx,Net/Rate/Tx"
+	$vboxmanage metrics setup --period 1 --samples 1 "$DOCKER_MACHINE_NAME"
+	sleep 1
+	$vboxmanage metrics query "$DOCKER_MACHINE_NAME" $metrics
+}
+
+vm-ram () {
+	echo "Current $(VBoxManage showvminfo "$DOCKER_MACHINE_NAME" | grep Memory)"
+	if [[ "$1" != "" ]]; then
+		local running
+		is_docker_machine_running && running=1
+		_confirm "Continue changing Memory size to ${1}MB?"
+		[[ $running == 1 ]] && docker_machine_stop
+		$vboxmanage modifyvm "$DOCKER_MACHINE_NAME" --memory "$1" && \
+			echo "Memory size updated."
+		[[ $running == 1 ]] && docker_machine_start
+	fi
+}
+
+#------------------------------- Other Commands -----------------------------------
 
 # Start containers
 up ()
@@ -893,29 +973,12 @@ down ()
 	_stop_containers "$@"
 }
 
-# Stop docker-machine
-halt ()
-{
-	if is_linux; then
-		down
-	else
-		docker_machine_stop
-	fi
-}
-
 # Restart container(s)
 # @param $1 container_name
 restart ()
 {
 	check_dsh_environment
 	_restart_containers "$@"
-}
-
-# Restart docker-machine and start containers again
-reload ()
-{
-	(is_mac || is_windows) && halt
-	up
 }
 
 # output status of Drude if stopped or containers if started
@@ -930,30 +993,6 @@ status ()
 		check_dsh_environment
 		docker_compose ps
 	fi
-}
-
-vmstat ()
-{
-	check_docker_running
-	if ! is_binary_found vboxmanage; then
-		echo-error "vboxmanage was not found" && exit 1
-	fi
-	metrics="CPU/Load/User,CPU/Load/Kernel,Disk/Usage/Used,RAM/Usage/Used,Net/Rate/Rx,Net/Rate/Tx"
-	$vboxmanage metrics setup --period 1 --samples 1 "$DOCKER_MACHINE_NAME"
-	sleep 1
-	$vboxmanage metrics query "$DOCKER_MACHINE_NAME" $metrics
-}
-
-_ip ()
-{
-	check_docker_running
-	docker-machine ip "$DOCKER_MACHINE_NAME"
-}
-
-_env ()
-{
-	check_docker_running
-	docker-machine env "$DOCKER_MACHINE_NAME"
 }
 
 # Add key to ssh-agent or run ssh-add with provided @param
@@ -1796,15 +1835,9 @@ case $1 in
 		shift
 		down "$@"
 		;;
-	halt)
-		halt
-		;;
 	restart)
 		shift
 		restart "$@"
-		;;
-	reload)
-		reload
 		;;
 	status)
 		shift
@@ -1817,6 +1850,10 @@ case $1 in
 	ps)
 		shift
 		status "$@"
+		;;
+	vm)
+		shift
+		vm "$@"
 		;;
 	vmstat)
 		vmstat
