dsh: windows prerequisites installation

diff --git a/bin/dsh b/bin/dsh
--- a/bin/dsh
+++ b/bin/dsh
@@ -376,19 +376,31 @@ status ()
 	fi
 }
 
+# installation and updates
+
 install_prerequisites() 
 {
 	echo -e "${green}Installing prerequisites...${NC}"
 	if is_windows ; then
-		echo -e "${red}dsh: prerequisites install is not automated on Windows yet.$NC"
-		_confirm "Do you already have them installed manually?"
+		local presetup_script=$(curl -fsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/presetup-win.cmd)
+		if [ ! $? -eq 0 ]; then
+			echo -e "${red}Could not get 'presetup-win.cmd'. Please check your internet connection${NC}"
+			exit
+		fi
+		local presetup_vbs=$(curl -fsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/presetup-git-bash.vbs)
+		if [ ! $? -eq 0 ]; then
+			echo -e "${red}Could not get 'presetup-git-bash.vbs'. Please check your internet connection${NC}"
+			exit
+		fi
+		echo "Setup needs administrator privileges to contiue..."
+		cscript "presetup-git-bash.vbs"
 	elif is_linux ; then
 		echo -e "${red}dsh: prerequisites install is not automated on Linux yet.$NC"
 		_confirm "Do you already have them installed manually?"
 	else # mac
 		local presetup_script=$(curl -fsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/presetup-mac.sh)
 		if [ ! $? -eq 0 ]; then
-			echo -e "${red}Could not get latest boot2docker version. Please check your internet connection${NC}"
+			echo -e "${red}Could not get 'presetup-mac.sh'. Please check your internet connection${NC}"
 			exit
 		fi
 		bash <(echo "$presetup_script")
@@ -403,7 +415,7 @@ install_boot2docker()
 	echo -n "Downloading boot2docker install script..."
 	local b2d_setup_script=$(curl -fsS https://raw.githubusercontent.com/blinkreaction/boot2docker-vagrant/$B2D_BRANCH/setup.sh)
 	if [ ! $? -eq 0 ]; then
-		echo -e "${red}Could not get latest boot2docker version. Please check your internet connection${NC}"
+		echo -e "${red}Could not get 'setup.sh'. Please check your internet connection${NC}"
 		exit
 	fi
 	echo "done"
@@ -430,11 +442,11 @@ install ()
 {
 	local cwd=$(pwd)
 	cd ..
-	_confirm "Will install Vagrantfile to $(pwd)"
+	_confirm "Install Vagrantfile to $(pwd)?"
 	install_prerequisites
 	install_boot2docker
 	cd $cwd
-	_confirm "Will install docker-compose.yml to $(pwd)"
+	_confirm "Install docker-compose.yml to $(pwd)?"
 	install_drude
 	echo -e "${red}Please restart you terminal shell$NC"
 }
