1.99.63 Adapt check_binary_found for Linux

diff --git a/bin/dsh b/bin/dsh
--- a/bin/dsh
+++ b/bin/dsh
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-DSH_VERSION=1.99.62
+DSH_VERSION=1.99.63
 
 # Console colors
 red='\033[0;91m'
@@ -334,8 +334,16 @@ is_binary_found ()
 # checks if binary exists and fails is it isn't
 check_binary_found ()
 {
-	[[ -x "$DRUDE_BIN_DIR/$1" ]]
-	if_failed "$1 executable was not found in $DRUDE_BIN_DIR. (Try running 'dsh install prerequisites')"
+	if [[ -x "$DRUDE_BIN_DIR/$1" ]] || (is_linux && $(which $1)); then
+		return 0
+	else
+		if is_linux; then
+			echo-red "$1 executable was not found. (Try running 'dsh install prerequisites')"
+		else
+			echo-red "$1 executable was not found in $DRUDE_BIN_DIR. (Try running 'dsh install prerequisites')"
+		fi
+		exit 1
+	fi
 }
 
 is_docker_running ()
@@ -1661,7 +1669,7 @@ install_prerequisites_ubuntu ()
 	if ! is_docker_version; then
 	echo-green "Installing Docker..."
 		# Stop docker dervice if it exists
-		if ps aux | grep dockerd | grep -v grep 2>/dev/null; then
+		if ps aux | grep dockerd | grep -v grep >/dev/null 2>/dev/null; then
 			echo "Stopping docker service..."
 			sudo service docker stop 2>/dev/null
 		fi
