Fix for network issues after project stop/restart
- Reordered operations:
  - "fin project start": dc create => (re)connect network => dc start
  - "fin project stop": dc stop => disconnect & delete network
- Updated tests

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -1357,6 +1357,9 @@ _disconnect_project_network ()
 	done
 }
 
+# This starts/restart the project start.
+# The order of actions is important in the case of restart, since we manipulate the project network.
+# Order: (re)create => (re)connect network => start.
 _start_containers ()
 {
 	check_docker_running
@@ -1366,18 +1369,26 @@ _start_containers ()
 	# Note: triggering this check in load_configuration would introduce a blocker for many fin commands.
 	check_docker_path
 
-	# Suppress docker pull details in CI environments otherwise pull prints too much garbage in CI logs.
-	is_ci && quiet_pull="--quiet-pull" || quiet_pull=""
+	# (Re)create project resources
+	# This will recraete the project network if missing.
+	# docker-compose create &>/dev/null || (echo-error "Failed to create project resources"; return 1)
+	echo-yellow "(Re)creating resources..."
+	docker-compose create --no-recreate || return 1
 
-	echo-green "Starting services..."
-	docker-compose up -d --remove-orphans --build ${quiet_pull} || return 1
+	# (Re)connect containers to project network
+	# We have to manually reconnect project containers to project network (after restart).
+	_connect_project_network
 	# TODO: Workaround. Handle this case in docksal/vhost-proxy.
 	# When project stack is started, but vhost-proxy is not yet connected to the stack network, vhost-proxy config breaks.
 	# To mitigate this we should connect vhost-proxy to the project stack network ASAP.
 	_vhost_proxy_connect
-	# Workaround for Docker Compose v2
-	# We have to manually reconnect project containers to project network
-	_connect_project_network
+
+	# Start project containers
+	# Suppress docker pull details in CI environments otherwise pull prints too much garbage in CI logs.
+	is_ci && quiet_pull="--quiet-pull" || quiet_pull=""
+	echo-yellow "Starting services..."
+	docker-compose up -d --remove-orphans --build ${quiet_pull} || return 1
+
 	_healthcheck_wait
 }
 
@@ -1429,13 +1440,16 @@ _stop_containers ()
 	load_configuration
 	check_project_unique
 
+	echo-yellow "Stopping services..."
+	docker-compose stop "$@"
+
 	# TODO: Do we still need this?
 	# While Docker Compose v2 recreates the project network if one does not exist,
 	# it does not reconnect project containers to the project network.
 	# If we delete the project network, we have to then manually reconnect project containers to the project network.
 	# See _connect_project_network
 	if [[ $1 == '-a' ]] || [[ $1 == '--all' ]] || [[ -z $1 ]]; then
-		echo-green "Disconnecting project network..."
+		echo-yellow "Disconnecting project network..."
 		# There is a limit of about 30 docker networks per host, so unused (stopped projects') networks should be dropped.
 		# The project network will be automatically recreated by docker-compose up.
 		local network="${COMPOSE_PROJECT_NAME_SAFE}_default"
@@ -1443,9 +1457,6 @@ _stop_containers ()
 
 		docker network rm "${network}" &>/dev/null || true
 	fi
-
-	echo-green "Stopping services..."
-	docker-compose stop "$@"
 }
 
 _restart_containers ()
@@ -1458,7 +1469,7 @@ _remove_containers ()
 {
 	check_project_environment
 	if [[ $1 == "" ]]; then
-		echo-yellow "Removing containers..."
+		echo-yellow "Removing resources..."
 
 		# Disconnect all containers from the project network, otherwise network will not be removed.
 		# Figure out the default project network name
