1.30.1 check nslookup binary in configure_resolver. Fixed #314

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-FIN_VERSION=1.30.0
+FIN_VERSION=1.30.1
 
 # Console colors
 red='\033[0;91m'
@@ -2706,20 +2706,23 @@ configure_resolver ()
 	if [[ "$mode" != "off" ]]; then
 		echo-green "Enabling automatic *.$DOCKSAL_DNS_DOMAIN DNS resolver..."
 
-		# Probing the upstream DNS server
-		# We want to make sure the upstream DNS server is reachable before configuring the host to use our DNS service.
-		# If it's not reachable, hosts DNS resolution may be affected or stop working entirely.
-		# nslookup returns 0 exit code regardless of the results, so have to pipe it ot grep
-		nslookup -timeout=1 google.com "$DOCKSAL_DNS_UPSTREAM" 2>/dev/null | grep google.com >/dev/null
-		local ret=$?
+		# The following check requires nslookup. Skip it if the binary is not present.
+		if ! (which nslookup >/dev/null 2>&1); then
+			# Probing the upstream DNS server
+			# We want to make sure the upstream DNS server is reachable before configuring the host to use our DNS service.
+			# If it's not reachable, hosts DNS resolution may be affected or stop working entirely.
+			# nslookup returns 0 exit code regardless of the results, so have to pipe it ot grep
+			nslookup -timeout=1 google.com "$DOCKSAL_DNS_UPSTREAM" 2>/dev/null | grep google.com >/dev/null
+			local ret=$?
 
-		if [[ "$ret" != "0" ]]; then
-			echo-error "The upstream DNS server ($DOCKSAL_DNS_UPSTREAM) is not reachable." \
-				"You are either offline, $DOCKSAL_DNS_UPSTREAM is not a valid DNS server or DNS requests to $DOCKSAL_DNS_UPSTREAM are blocked." \
-				"Once the current operation completes, follow the steps below:" \
-				"  1. Open ${yellow}~/.docksal/docksal.env${NC} and set ${yellow}DOCKSAL_DNS_UPSTREAM${NC} to your local network DNS server" \
-				"  2. Run ${yellow}fin reset dns${NC} to see if it works"
-			_confirm "Continue?"
+			if [[ "$ret" != "0" ]]; then
+				echo-error "The upstream DNS server ($DOCKSAL_DNS_UPSTREAM) is not reachable." \
+					"You are either offline, $DOCKSAL_DNS_UPSTREAM is not a valid DNS server or DNS requests to $DOCKSAL_DNS_UPSTREAM are blocked." \
+					"Once the current operation completes, follow the steps below:" \
+					"  1. Open ${yellow}~/.docksal/docksal.env${NC} and set ${yellow}DOCKSAL_DNS_UPSTREAM${NC} to your local network DNS server" \
+					"  2. Run ${yellow}fin reset dns${NC} to see if it works"
+				_confirm "Continue?"
+			fi
 		fi
 	else
 		echo-green "Disabling automatic *.$DOCKSAL_DNS_DOMAIN DNS resolver..."
