Configure nfs.server.mount.require_resv_port = 0 automatically

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -2249,6 +2249,16 @@ nfs_share_add ()
 		echo "NFS shares are already configured"
 	fi
 
+	# Set nfs.server.mount.require_resv_port = 0
+	# Many NFS server implementations require this because of
+	# the false belief that this requirement increases security.
+	# Without this, NFS mounts are very likely to fail
+	if ! (cat /etc/nfs.conf | grep -e 'nfs\.server\.mount\.require_resv_port\s*=\s*0' >/dev/null); then
+		echo "Writing /etc/nfs.conf..."
+		echo "nfs.server.mount.require_resv_port = 0" | sudo tee -a /etc/nfs.conf >/dev/null
+		NFSD_RESTART_REQUIRED="true"
+	fi
+
 	# Start/Restart nfsd
 	(ps aux | grep /sbin/nfsd | grep -v grep >/dev/null) && NFSD_IS_RUNNING="true"
 	if [[ "$NFSD_IS_RUNNING" == "true" ]]; then
