run-cli (rc) should use 2.0 cli image. (#483)

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -3904,28 +3904,27 @@ run_cli ()
 	[[ $1 == "-T" ]] && \
 		local no_tty=true && shift
 	# Set default image
-	# Have to stick with docksal/1.3-php7 for now.
-	# TODO: Fix compatibility with docksal/cli:2.0 images.
-	local IMAGE="${IMAGE:-docksal/cli:1.3-php7}"
+	local IMAGE="${IMAGE:-docksal/cli:2.0-php7.1}"
 	local cmd="$@"
 
 	# Assume bash if no command was given
 	[[ "$cmd" == "" ]] && cmd="bash"
 
-	# Source $HOME/.docksalrc in cli.
-	# Commands in this file will be sourced for both interactive and non-interactive sessions.
-	DOCKSALRC='source $HOME/.docksalrc >/dev/null 2>&1'
-
 	# Debug mode off by default
 	DEBUG=${DEBUG:-0}
+
+	# Fail for images from v1, these are executing the commands directly and are not supported anymore.
+	if [[ "$IMAGE" == docksal/cli:1.* ]]; then
+		echo-error "run-cli command does not support the defined image. Please use docksal/cli:2.0 and above." && exit 1
+	fi
 
 	if is_tty && [[ "$no_tty" != true ]]; then
 		# interactive
 		# (exit \$?) is a hack to return correct exit codes when docker exec is run with tty (-t).
-		${winpty} docker run --rm -it -v $(pwd):/var/www -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -e DEBUG="$DEBUG" ${IMAGE} bash -ic "$DOCKSALRC; $cmd; (exit \$?)"
+		${winpty} docker run --rm -it -v $(pwd):/var/www -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -e DEBUG="$DEBUG" ${IMAGE} "$cmd; (exit \$?)"
 	else
 		# non-interactive
-		docker run --rm -v $(pwd):/var/www -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -e DEBUG="$DEBUG" ${IMAGE} bash -c "$DOCKSALRC; $cmd"
+		docker run --rm -v $(pwd):/var/www -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -e DEBUG="$DEBUG" ${IMAGE} "$cmd"
 	fi
 }
 
