Build 4

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -3111,12 +3111,20 @@ install_tools_ubuntu ()
 install_tools_wsl ()
 {
 	# Install Docker client
-	if ! is_docker_version; then
-		echo-green "Installing Docker..."
-		sudo apt update
-		sudo apt install docker.io
-		if_failed "Docker installation/upgrade has failed."
-	fi
+#	if ! is_docker_version; then
+#		echo-green "Installing Docker..."
+#		# Install packages to allow apt to use a repository over HTTPS
+#		$ sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
+#		# Add Docker's official GPG key
+#		$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+#		# Set up the repository
+#		sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+#		# Update source lists
+#		sudo apt-get update
+#		# Install Docker
+#		sudo apt-get install docker-ce -y --allow-unauthenticated
+#		if_failed "Docker installation/upgrade has failed."
+#	fi
 
 	# Install Docker Compose
 	if ! is_docker_compose_version; then
