0.11.0 Rewrite mysql related functions
* mysql-import and mysql-dump are not Drupal-related anymore and require database name
* mysql-import can only handle plain files now (utilities naming issue gzcat/zcat blocks stable solution for gzipped files)
* "vm rm" renamed to "vm remove"
* rewrite help

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-FIN_VERSION=0.10.1
+FIN_VERSION=0.11.0
 
 # Console colors
 red='\033[0;91m'
@@ -731,15 +731,18 @@ printh ()
 	case "$3" in
 		yellow)
 			printf "\t${yellow}%-${COMMAND_COLUMN_WIDTH}s${NC}" "$1"
+			echo -e "	 $2"
 			;;
 		green)
 			printf "\t${green}%-${COMMAND_COLUMN_WIDTH}s${NC}" "$1"
+			echo -e "	 $2"
 			;;
 		*)
 			printf "\t%-${COMMAND_COLUMN_WIDTH}s" "$1"
+			echo -e "	$2"
 			;;
 	esac
-	echo -e "	$2"
+
 }
 
 # Show help for fin or for certain command
@@ -775,43 +778,44 @@ show_help ()
 	printh "Docksal Fin v$FIN_VERSION commands reference" "" "green"
 
 	echo
+	if ! is_linux && ! is_docker_native; then
+		printh "vm <command>" "Docksal's Virtualbox machine commands (${yellow}fin help vm${NC})" "yellow"
+	fi
+
+	echo
 	if is_linux; then
 		printh "start (up)" "Start project services"
 	else
-		printh "start (up)" "Start docker machine and project services"
+		printh "start (up)" "Start virtualbox machine and project services"
 	fi
-	printh "stop [-a (--all)]" "Stop project services. -a stops all containers except Docksal system services"
+	printh "stop [-a (--all)]" "Stop project services (-a stops all services on all projects)"
 	printh "restart" "Restart all current project services"
-	printh "status (ps) [-a (--all)]" "Show project services status. -a shows all running containers"
-	printh "reset [service]" "Recreate all all selected project service(s). (${yellow}fin help reset${NC})"
-	printh "rm [service]" "Remove project or system services. See ${yellow}fin help rm${NC}"
-	if ! is_linux && ! is_docker_native; then
-		printh "vm <command>" "Control docker machine vm. See ${yellow}fin help vm${NC} for commands list" "yellow"
-	fi
+	printh "status (ps) [-a (--all)]" "Show project services status (-a shows all running containers)"
+	printh "reset [service]" "Recreate project services and containers (${yellow}fin help reset${NC})"
+	printh "rm [service]" "Remove project services (${yellow}fin help rm${NC})"
 
 	echo
-	printh "bash [service]" "Open shell into container. Defaults to ${yellow}cli${NC} service"
-	printh "exec <command> [params]" "Execute a command in ${yellow}cli${NC} service container"
-	printh "exec-url <url>" "Download script from URL and run it. URL should be public."
-	printh "logs [service]" "Show docker logs for service container"
+	printh "bash [service]" "Open shell into container. Defaults to ${yellow}cli${NC}"
+	printh "exec <command> [params]" "Execute a command in ${yellow}cli${NC}"
+	printh "exec-url <url>" "Download script from URL and run it on host (URL should be public)"
+	printh "logs [service]" "Show Docker logs for service container"
 
 	echo
-	printh "drush [command] [options]" "Execute Drush command (Drupal)"
-	printh "drupal [command] [options]" "Execute Drupal Console command (Drupal 8)"
-	printh "wp [command] [options]" "Execute WP-CLI command (WordPress)"
+	printh "drush [command]" "Execute Drush command (Drupal)"
+	printh "drupal [command]" "Execute Drupal Console command (Drupal 8)"
+	printh "wp [command]" "Execute WP-CLI command (WordPress)"
 
 	echo
-	printh "mysql (sqlc)" "Opens mysql shell to current project database"
-	printh "mysql-dump [file]" "Dump current project database into file (${yellow}fin help mysql-dump${NC})"
-	printh "mysql-import (sqli) <file>" "Truncate database and import from sql dump (file should be accessible to Docksal)"
-	printh "" "See ${yellow}fin help sqli${NC} for advanced usage (multisite, gz)."
+	printh "sqlc" "Opens mysql shell to current project database (alias: mysql)"
+	printh "sqld <database> <file>" "Dump specified database into file (${yellow}fin help sqld${NC})"
+	printh "sqli <database> <file>" "Truncate this database and import from sql dump (${yellow}fin help sqli${NC})"
 
 	echo
 	printh "behat [--path=path]" "Run Behat tests from path relative to YML path. Default: tests/behat"
 	printh "ssh-add [-lD] [key]" "Adds private key identities to the authentication agent (${yellow}fin help ssh-add${NC})"
 
 	echo
-	printh "alias" "Create/remove aliases (${yellow}fin help alias${NC})"
+	printh "alias" "Create/remove folder aliases (${yellow}fin help alias${NC})"
 	printh "config" "Display/generate project configuration (${yellow}fin help config${NC})"
 	printh "cleanup [--hard]" "Remove unused docker images (--hard will also remove stopped containers)"
 	printh "sysinfo" "Show diagnostics information for bug reporting"
@@ -934,38 +938,36 @@ show_help_exec-url ()
 
 show_help_sqli ()
 {
-	echo-green "fin sqli <db_dump_file> - Import DB dump into database truncating it first"
+	echo-green "Import SQL DB dump into the database, truncating it first (alias: mysql-import)"
+	printh "fin sqli <database> <dump_file.sql>" "" "yellow"
 	echo
-	echo -e "DB dump file can be either plain ${yellow}.sql${NC} file or gzipped ${yellow}.sql.gz${NC}."
-	echo -e "To import dump into sub-site cd into sub-site folder ${yellow}cd docroot/sites/sub-site${NC} and run fin sqli from there."
+	echo -e "DB dump file should be plain ${yellow}.sql${NC} file."
 	echo
 	echo-green "Examples:"
-	printh "fin sqli ../../mydump.sql" "Import plaintext sql dump"
-	printh "fin sqli otherdump.sql.gz" "Import gzipped sql dump"
+	printh "fin sqli drupal ../../mydump.sql" "Import plaintext sql dump into 'drupal' database"
 	echo
 }
-
 show_help_mysql-import ()
 {
 	show_help_sqli
 }
 
-show_help_mysql-dump ()
+show_help_sqld ()
 {
-	echo-green "fin mysql-dump [dump_file] - Export current database into file"
+	echo-green "Export database from db container into file (alias: mysql-dump)"
+	printh "fin sqld <database> <dump_file>" "" "yellow"
 	echo
-	echo "Current database depends on context. Running from docroot will use default subsite"
-	echo "while running this command from specific subsite folder will use that subsite's db settings."
-	echo
-	echo-green "Parameters:"
-	printh "--db-user=admin" "Use another mysql username (default is 'drupal')"
-	printh "--db-password=p4\$\$" "Use another database password (default is '123')"
-	printh "--db-name=mydb2" "Specify database name to dump. Default is currently used one."
+	echo-green "Optional parameters:"
+	printh "--db-user=admin" "Use another mysql username (default is the one set with 'MYSQL_USER')"
+	printh "--db-password=p4\$\$" "Use another database password (default is the one set with 'MYSQL_PASSWORD')"
 	echo
 	echo-green "Examples:"
-	printh "fin mysql-dump /tmp/dump.sql" "Export into /tmp/dump.sql"
-	printh "fin mysql-dump" "Export into stdout"
+	printh "fin sqld drupal ~/dump.sql" "Export database 'drupal' into ~/dump.sql"
 	echo
+}
+show_help_mysql-dump ()
+{
+	show_help_sqld
 }
 
 show_help_vm ()
@@ -980,9 +982,9 @@ show_help_vm ()
 	printh "status" "Get the status of a machine"
 	printh "ls" "List all docker machines"
 	printh "ssh" "Log into or run a command on the active machine with SSH"
-	printh "rm" "Remove active machine"
+	printh "remove" "Remove active machine"
 	printh "ip" "Get machine IP address"
-	printh "ip [new ip]" "Set machine IP address (requires vm restart)"
+	# printh "ip [new ip]" "Set machine IP address (requires vm restart)"
 	printh "env" "Display the commands to set up the shell for direct use of Docker client"
 	echo
 	printh "ram" "Get machine memory size"
@@ -1538,7 +1540,7 @@ vm ()
 		ls|list)
 			docker-machine ls
 			;;
-		rm)
+		remove)
 			shift
 			local machine_name="${1:-$DOCKER_MACHINE_NAME}"
 			docker_machine_remove "$machine_name"
@@ -2341,103 +2343,106 @@ mysql ()
 }
 
 # Truncate db and import from sql dump
-# @param $1 filename of backup file. Should be inside project root
+# @params
+# $1 - database name
+# $2 - file name
+# --db-user="admin" to override mysql username
+# --db-password="otherpass" to override mysql password
 mysql_import ()
 {
 	check_docksal_environment
-	check_drush_path
+	eval $(parse_params "$@")
 
-	local confirm=1
-	if [[ "$1" == "-y" ]] || [[ "$2" == "-y" ]]; then
-		confirm=0
-		if [[ "$1" == "-y" ]]; then
-			shift #remove this param if -y was first
-		fi
+	local __dump_user="${dbuser:-\$MYSQL_USER}"
+	local __dump_password="${dbpassword:-\$MYSQL_PASSWORD}"
+	local __database="${ARGV[0]}"
+	local __input="${ARGV[1]}"
+
+	if [[ "${ARGV[0]}" == "" ]] || [[ "${ARGV[1]}" == "" ]]; then
+		show_help_mysql-import
+		echo-green "Available databases:"
+		_RUN_NO_CDIR=1 CONTAINER_NAME="db" \
+			_run "echo 'show databases' | mysql -u $__dump_user -p${__dump_password}"
+		exit 1
 	fi
 
-	project_root=$(get_docksal_path)
-	local filename=$(basename $1)
-	local filepath=$(get_abs_path $1)
-	#substract project root path from filepath
-	local pathdiff=${filepath#$project_root}
+	[[ ! -r "$__input" ]] &&
+		echo-error "Can not read $__input" "Please check file path and permissions" && exit 1
 
-	if [[ "$pathdiff" == "$filepath" ]] ; then
-		# substraction did not succeed because file is outside project root
-		echo "\"$filename\" should be inside your project root folder"
-		return
+	local confirm=0
+	if [[ "$force" == "force" ]]; then
+		confirm=1
 	fi
 
-	if [ ${confirm} -eq 1 ]; then
-		_confirm "[!] This will drop the existing database. Continue?"
-	fi
+	#-- 1) TRUNCATING
+	echo "Truncating '$__database'..."
+	# next line should go in one line to be treated as a single command by _run and have pipe being run on container side
+	local TRUNCATE_DATABASE_COMMAND="mysqldump -u$__dump_user -p$__dump_password --add-drop-table --no-data $__database | grep -e '^DROP \| FOREIGN_KEY_CHECKS' | mysql -u$__dump_user -p$__dump_password $__database"
 
-	#_run drush sql-drop -y
-	local sql_connect
-	sql_connect=$(get_mysql_connect)
-	echo "Importing $filename into the database..."
+	_RUN_NO_CDIR=1 CONTAINER_NAME="db" \
+		_run "${TRUNCATE_DATABASE_COMMAND}"
 
-	# Use pv for interactive shells only.
-	if is_tty ; then
-		# Check if we have a gzipped dump and treat it differently.
-		if [[ "$filename" == *.gz ]]; then
-			file_size=$(gzip -l $1 | sed -n 2p | awk '{print $2}')
-			RUN_NO_CDIR=1 _run "zcat ./$pathdiff/$filename | pv --size $file_size | $sql_connect"
-		else
-			RUN_NO_CDIR=1 _run "pv ./$pathdiff/$filename | $sql_connect"
-		fi
+	if [[ ! $? -eq 0 ]] && (exit ${confirm}); then
+		_confirm "There were errors during truncation. Continue anyways?"
 	else
-		# Check if we have a gzipped dump and treat it differently.
-		if [[ "$filename" == *.gz ]]; then
-			RUN_NO_CDIR=1 _run "zcat ./$pathdiff/$filename | $sql_connect"
-		else
-			RUN_NO_CDIR=1 _run "cat ./$pathdiff/$filename | $sql_connect"
-		fi
+		echo-rewrite-ok "Truncating '$__database'..."
 	fi
+
+	#-- 2) IMPORTING
+	echo "Importing..."
+	# We can not use _run here because we need to launch docker exec with only -i param
+	# and only mysql command direclty (no bash wrapper) so that stdin could be received inside that exec
+	is_windows && check_binary_found 'winpty' && winpty_cmd='winpty'
+	container_id=$(get_container_id "db")
+	__mysql_command=$(_RUN_NO_CDIR=1 CONTAINER_NAME="db" _run "echo mysql -u$__dump_user -p$__dump_password")
+	__mysql_command=$(echo $__mysql_command | sed -e 's/[^a-zA-Z0-9_-]$//')
+	cat "$__input" | ${winpty_cmd} docker exec -i "$container_id" ${__mysql_command} ${__database}
 
 	# Check if import succeded or not and print results.
 	if [ $? -eq 0 ]; then
-		echo-green "mysql-import finished";
+		echo-rewrite-ok "Importing..."
 		if is_tty; then _notify "Docksal" "Mysql import finished"; fi
+		exit 0
 	else
-		echo-red "mysql-import failed";
+		echo-red "Import failed";
 		if is_tty; then _notify "Docksal" "Mysql import failed!"; fi
+		exit 1
 	fi
 }
 
 # Dump mysql database
-# Params
-# --db-name="otherdb" to override database name. default is currenly used db
+# @params
+# $1 - database name
+# $2 - file name
 # --db-user="admin" to override mysql username
 # --db-password="otherpass" to override mysql password
 mysql_dump ()
 {
+	check_docksal_environment
 	eval $(parse_params "$@")
 
-	echo-green "Looking for database..."
-	local database_name=$(_run drush "status" | grep "Database name" | sed "s/^.*\://")
-	# trim whitespace
-	database_name=$(echo -n "${database_name//[[:space:]]/}")
-	if [[ "$database_name" == "" ]]; then
-		echo-error "Could not find database name" "Are you running from docroot?"
-		return 1
+	local __dump_user="${dbuser:-\$MYSQL_USER}"
+	local __dump_password="${dbpassword:-\$MYSQL_PASSWORD}"
+	local __database="${ARGV[0]}"
+	local __output="${ARGV[1]}"
+
+	if [[ "${ARGV[0]}" == "" ]] || [[ "${ARGV[1]}" == "" ]]; then
+		show_help_mysql-dump
+		echo-green "Available databases:"
+		_RUN_NO_CDIR=1 CONTAINER_NAME="db" \
+			_run "echo 'show databases' | mysql -u $__dump_user -p${__dump_password}"
+		exit 1
 	fi
 
-	if [[ "$dbname" != '' ]]; then
-		database_name="$dbname"
-	fi
-	local __dump_user="${dbuser:-drupal}"
-	local __dump_password="${dbpassword:-123}"
+	touch "$__output"
+	if_failed_error "Could not write $__output" "Please check your file permissions"
 
 	echo-green "Exporting..."
-	if [[ "${ARGV[0]}" != "" ]]; then
-		_RUN_NO_CDIR=1 CONTAINER_NAME="db" _run \
-			"mysqldump -u $__dump_user -p${__dump_password} $database_name" | tee >/dev/null "${ARGV[0]}"
-	else
-		_RUN_NO_CDIR=1 CONTAINER_NAME="db" _run \
-			"mysqldump -u $__dump_user -p${__dump_password} $database_name"
-	fi
 
-	echo-green "Done"
+	_RUN_NO_CDIR=1 CONTAINER_NAME="db" \
+		_run "mysqldump -u $__dump_user -p${__dump_password} $__database" | tee "$__output" >/dev/null
+
+	[ $? -eq 0 ] && echo-rewrite-ok "Exporting... [done]"
 }
 
 # Run Behat tests (also install dependencies through Composer)
@@ -2947,9 +2952,10 @@ case "$1" in
 		mysql
 		;;
 	mysql-import|sqli)
-		mysql_import "$2" "$3"
+		shift
+		mysql_import "$@"
 		;;
-	mysql-dump)
+	mysql-dump|sqld)
 		shift
 		mysql_dump "$@"
 		;;
