Added "DOCKSAL: NETWORKING" sections in sysinfo
- Replaced "DOCKSAL: DNS"
- Prints network config variables
- Added check for DNS resolution/connectivity from containers (and not only host)

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -5960,15 +5960,29 @@ sysinfo ()
 		vhosts
 
 		echo
-		echo "███  DOCKSAL: DNS"
-		[[ ${DOCKSAL_DNS_DISABLED} == 0 ]] && echo "Enabled" || echo "Disabled"
+		echo "███  DOCKSAL: NETWORKING"
+		echo
+		echo "DOCKSAL_IP: ${DOCKSAL_IP}"
+		echo "DOCKSAL_VHOST_PROXY_IP: ${DOCKSAL_VHOST_PROXY_IP}"
+		echo "DOCKSAL_DNS_IP: ${DOCKSAL_DNS_IP}"
+		echo "DOCKSAL_DNS_DISABLED: ${DOCKSAL_DNS_DISABLED}"
+		echo "DOCKSAL_NO_DNS_RESOLVER: ${DOCKSAL_NO_DNS_RESOLVER}"
+		echo "DOCKSAL_DNS_UPSTREAM: ${DOCKSAL_DNS_UPSTREAM}"
+		echo "DOCKSAL_DNS_DOMAIN: ${DOCKSAL_DNS_DOMAIN}"
+		echo
 		TEST_URL="http://dns-test.${DOCKSAL_DNS_DOMAIN}"
-		curl --connect-timeout 2 -sS "${TEST_URL}" >/dev/null
-		if [[ $? != 0 ]]; then
-			echo "ERROR: Requesting ${TEST_URL} failed!"
-		else
-			echo "Successfully requested ${TEST_URL}"
-		fi
+		#TEST_CMD="wget -O- ${TEST_URL} &>/dev/null"  # Does not work correctly with Alpine's buysbox/wget
+		TEST_CMD="curl --connect-timeout 2 -sS ${TEST_URL}"
+		echo "Checking connectivity to ${TEST_URL}..."
+		# Test DNS resolution on the host
+		echo -n "Host: "
+		eval ${TEST_CMD} &>/dev/null
+		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
+		# Test DNS resolution in a container
+		echo -n "Containers: "
+		# TODO: figure out how to use busybox/wget in docksal/empty or use our own version with full wget/curl instead
+		docker run --rm --dns="${DOCKSAL_DNS1}" --dns="${DOCKSAL_DNS2}" curlimages/curl sh -c "${TEST_CMD}" &>/dev/null
+		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
 
 		echo
 		echo "███  DOCKER: RUNNING CONTAINERS"
