0.1.12. DOCKER_BETA renamed to DOCKER_NATIVE

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-FIN_VERSION=0.1.11
+FIN_VERSION=0.1.12
 
 # Console colors
 red='\033[0;91m'
@@ -88,7 +88,7 @@ IMAGE_DNS="blinkreaction/dns-discovery"
 #---------------------------- Global Variables --------------------------------
 
 PATH="$CONFIG_BIN_DIR:$PATH"
-DOCKER_BETA="${DOCKER_BETA:-0}"
+DOCKER_NATIVE="${DOCKER_NATIVE:-0}"
 # Allow image tag overrides for system services. See install_xyz_service()
 # TODO: revert this to stable before release
 #FIN_ITAG="${FIN_ITAG:-stable}"
@@ -96,7 +96,7 @@ FIN_ITAG="${FIN_ITAG:-latest}"
 # UID of user to use in cli continer. Only override if you know what you're doing
 FIN_SET_UID=""
 
-if [[ "$DOCKER_BETA" == "1" ]]; then
+if [[ "$DOCKER_NATIVE" == "1" ]]; then
 	# no vm used
 	export DOCKER_HOST=""
 else
@@ -230,7 +230,7 @@ docker_compose ()
 	# Running docker exec interactively on Windows requires workarounds
 	is_windows && check_binary_found 'winpty' && winpty_cmd='winpty'
 	is_linux && DOCKER_COMPOSE_BIN="$DOCKER_COMPOSE_BIN_NIX"
-	is_docker_beta && DOCKER_COMPOSE_BIN="docker-compose"
+	is_docker_native && DOCKER_COMPOSE_BIN="docker-compose"
 	# docker-compose cannot find docker-compose.yml in the path if there are symlinks on the way
 	# get_yml_path can properly find the file. Incapsulate the cd into subshell
 	(cd "$(get_yml_path)" && "$DOCKER_COMPOSE_BIN" "$@")
@@ -331,16 +331,16 @@ is_mac ()
 	uname | grep 'Darwin' >/dev/null
 }
 
-is_docker_beta ()
+is_docker_native ()
 {
 	# comparison returns error codes
-	[[ "$DOCKER_BETA" == "1" ]]
+	[[ "$DOCKER_NATIVE" == "1" ]]
 }
 
 # checks if binary exists and fails is it isn't
 check_binary_found ()
 {
-	if [[ -x "$CONFIG_BIN_DIR/$1" ]] || ( (is_linux || is_docker_beta) && which "$1" 2>/dev/null >/dev/null ); then
+	if [[ -x "$CONFIG_BIN_DIR/$1" ]] || ( (is_linux || is_docker_native) && which "$1" 2>/dev/null >/dev/null ); then
 		return 0
 	else
 		if is_linux; then
@@ -354,7 +354,7 @@ check_binary_found ()
 
 is_docker_running ()
 {
-	if ! is_linux && ! is_docker_beta; then
+	if ! is_linux && ! is_docker_native; then
 		if ! is_docker_machine_running; then return 255; fi
 	fi
 	# Check if docker is running via docker info.
@@ -400,19 +400,19 @@ check_docker_running ()
 
 	check_binary_found 'docker'
 	check_binary_found 'docker-compose'
-	if ! is_docker_beta && ! is_docker_version; then
+	if ! is_docker_native && ! is_docker_version; then
 		echo-error "Required Docker version is $REQUIREMENTS_DOCKER or higher"
 		echo -e "Run ${yellow}fin update tools${NC} to update"
 		exit 1
 	fi
-	if is_docker_beta && ! is_docker_version; then
+	if is_docker_native && ! is_docker_version; then
 		echo-yellow "Your Docker version is out of date. Please update to $REQUIREMENTS_DOCKER"
 	fi
 
 	is_docker_running
 	docker_status=$?
 
-	if [[ ${docker_status} -eq 255 ]] && ! is_docker_beta; then
+	if [[ ${docker_status} -eq 255 ]] && ! is_docker_native; then
 		echo-yellow "It looks like '$DOCKER_MACHINE_NAME' docker machine is not running."
 		_confirm "Run 'fin vm start' to start it now?"
 		docker_machine_start
@@ -426,7 +426,7 @@ check_docker_running ()
 	if [[ $docker_status -eq 0 ]]; then
 		DOCKER_RUNNING="true"
 	else
-		if is_docker_beta; then
+		if is_docker_native; then
 			exit 1
 		else
 			echo-error "Looks like your Docker client and Docker server are incompatible." \
@@ -733,7 +733,7 @@ show_help ()
 	printh "reset [service]" "Recreate service(s). If no parameter given recreates all project services."
 	printh "" "See ${yellow}fin help reset${NC} for more details on resetting Docksal system services."
 	printh "remove [service]" "Remove project or system services. See ${yellow}fin help remove${NC}"
-	if ! is_linux && ! is_docker_beta; then
+	if ! is_linux && ! is_docker_native; then
 		printh "vm <command>" "Control docker machine vm. See ${yellow}fin help vm${NC} for commands list" "yellow"
 	fi
 
@@ -1344,7 +1344,7 @@ docker_machine_mounts ()
 
 vm ()
 {
-	if is_docker_beta; then
+	if is_docker_native; then
 		return
 	fi
 
@@ -1540,7 +1540,7 @@ install_tools ()
 {
 	echo-green "Installing tools..."
 
-	if ! is_linux && ! is_docker_beta && which 'docker-machine' >/dev/null 2>&1; then
+	if ! is_linux && ! is_docker_native && which 'docker-machine' >/dev/null 2>&1; then
 		if is_docker_machine_exist && ! is_docker_machine_running; then
 			echo-error "Docker Machine '$DOCKER_MACHINE_NAME' exists but not running" \
 				"Start it with ${yellow}fin vm start${NC} first or destroy it with ${yellow}fin vm rm${NC} if you want it re-created."
@@ -1553,7 +1553,7 @@ install_tools ()
 		echo-green "Updating Docksal system images..."
 		update_system_images
 		# check latest boot2docker version
-		if ! is_linux && ! is_docker_beta; then
+		if ! is_linux && ! is_docker_native; then
 			local b2d_version=$(docker version --format '{{.Server.Version}}')
 			if [[ "$b2d_version" != "$REQUIREMENTS_DOCKER" ]]; then
 				BOOT2DOCKER_NEEDS_AN_UPGRADE=1
@@ -1618,7 +1618,7 @@ configure_resolver ()
 	local TARGET_IP="0.0.0.0"
 
 	if is_mac; then
-		if is_docker_beta; then
+		if is_docker_native; then
 			TARGET_IP="127.0.0.1"
 		else
 			TARGET_IP=$(docker-machine ip "$DOCKER_MACHINE_NAME")
@@ -1639,7 +1639,7 @@ configure_resolver ()
 		TARGET_IP="$DOCKSAL_DEFAULT_IP"
 		install_dns_service "$TARGET_IP"
 	elif is_windows; then
-		if is_docker_beta; then
+		if is_docker_native; then
 			TARGET_IP="127.0.0.1"
 		else
 			TARGET_IP=$(docker-machine ip "$DOCKER_MACHINE_NAME")
@@ -1660,7 +1660,7 @@ install_sshagent_service ()
 install_tools_mac ()
 {
 	is_tty || return 1 # only allow in interactive shell
-	is_docker_beta && echo "No tools installation required for native Docker" && return
+	is_docker_native && echo "No tools installation required for native Docker" && return
 
 	# Check VirtualBox
 	if ! which 'VBoxManage' >/dev/null 2>&1; then
@@ -1718,7 +1718,7 @@ install_tools_windows ()
 	mkdir -p "$CONFIG_DOWNLOADS_DIR" 2>/dev/null
 	if_failed "Could not create $CONFIG_DOWNLOADS_DIR"
 
-	if ! is_docker_beta; then
+	if ! is_docker_native; then
 		# Check Virtual Box
 		if ! is_vbox_version; then # TODO: check_vbox_version should say where it looks for vbox. Not found or versions wrong?
 			echo-error "Required Virtual Box version is $REQUIREMENTS_VBOX or higher" \
@@ -1774,7 +1774,7 @@ install_tools_windows ()
 	echo "git config --system core.longpaths true"
 	git config --system core.longpaths true # support long paths
 
-	if ! is_docker_beta; then
+	if ! is_docker_native; then
 		# If it was an upgrade
 		[[ "$BOOT2DOCKER_NEEDS_AN_UPGRADE" == "1" ]] && \
 			is_docker_machine_running && \
