Improved fin sysinfo output
Added green/red colors for PASS/FAIL tests

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -6217,15 +6217,15 @@ sysinfo ()
 		local PING="ping -c 1 -W 1"
 		echo -n "Host to ${DOCKSAL_IP}: 	"
 		eval "${PING} ${DOCKSAL_IP}" &>/dev/null
-		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
+		[[ $? == 0 ]] && echo-green "PASS" || echo-red "FAIL"
 		## Check that containers can access DOCKSAL_IP
 		echo -n "Container to ${DOCKSAL_IP}: 	"
 		docker run --rm busybox sh -c "${PING} ${DOCKSAL_IP}" &>/dev/null
-		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
+		[[ $? == 0 ]] && echo-green "PASS" || echo-red "FAIL"
 		## Check that containers can access DOCKSAL_HOST_IP
 		echo -n "Container to ${DOCKSAL_HOST_IP}: 	"
 		docker run --rm busybox sh -c "${PING} ${DOCKSAL_HOST_IP}" &>/dev/null
-		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
+		[[ $? == 0 ]] && echo-green "PASS" || echo-red "FAIL"
 
 		# DNS resolution
 		local TEST_URL="http://dns-test.${DOCKSAL_DNS_DOMAIN}"
@@ -6237,9 +6237,9 @@ sysinfo ()
 		echo -n "Host: "
 		eval ${TEST_CMD} &>/dev/null
 		if [[ $? == 0 ]]; then
-			echo "PASS"
+			echo-green "PASS"
 		else
-			echo "FAIL"
+			echo-red "FAIL"
 			echo
 			echo "Debug info:"
 			echo "----------"
@@ -6255,7 +6255,7 @@ sysinfo ()
 		echo -n "Containers: "
 		# TODO: figure out how to use busybox/wget in docksal/empty or use our own version with full wget/curl instead
 		docker run --rm --dns="${DOCKSAL_DNS1}" --dns="${DOCKSAL_DNS2}" curlimages/curl sh -c "${TEST_CMD}" &>/dev/null
-		[[ $? == 0 ]] && echo "PASS" || echo "FAIL"
+		[[ $? == 0 ]] && echo-green "PASS" || echo-red "FAIL"
 
 		echo
 		echo "███  DOCKER: RUNNING CONTAINERS"
